version: "3.8"
services:
  app:
    container_name: nekofighting-nest-server
    build:
      context: ./
      dockerfile: ./docker/nest/Dockerfile
    working_dir: /home/node/app
    command: npm run start:prod
    restart: unless-stopped
    tty: true
    networks:
      - nekofighting-nest-network
    depends_on:
      - database
    ports:
      - 5002:5002
    environment:
      APP_ENV: dev
      APP_PORT: 5002
      DB_DEBUG: 1
      DB_HOST: database
      DB_DATABASE: nekofighting
      DB_USERNAME: root
      DB_PASSWORD: 123456
      DB_PORT: 5432
      VERIFIED_MESSAGE: ${VERIFIED_MESSAGE}
      TOKEN_SECRET_KEY: ${TOKEN_SECRET_KEY}
      CACHE_HOST: ${CACHE_HOST}
      CACHE_PORT: ${CACHE_PORT}
      CACHE_DATABASE: ${CACHE_DATABASE}

  database:
    container_name: postgres-nekofighting-database
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - nekofighting-database:/var/lib/postgres
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: nekofighting
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 5430:5432
    networks:
      - nekofighting-nest-network

networks:
  nekofighting-nest-network:
    driver: bridge

volumes:
  nekofighting-database:
    driver: local
